// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteAppAPI.Context;

#nullable disable

namespace NoteAppAPI.Migrations
{
    [DbContext(typeof(NoteAppContext))]
    partial class NoteAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NoteAppAPI.Models.Entity.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2401),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Spor"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2411),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Online"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2412),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Sinema"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2413),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Müzik"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2414),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Cuma"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2414),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Perşembe"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2415),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Çarşamba"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2416),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Salı"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2417),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            IsDeleted = false,
                            Title = "Pazartesi"
                        });
                });

            modelBuilder.Entity("NoteAppAPI.Models.Entity.SubNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NoteId");

                    b.ToTable("SubNotes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2570),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 1
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2571),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 1
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2573),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 2
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2573),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 2
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2574),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 3
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2575),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 3
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2576),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 4
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2625),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 4
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2627),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 5
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2628),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 5
                        },
                        new
                        {
                            ID = 11,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2629),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 6
                        },
                        new
                        {
                            ID = 12,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2629),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 6
                        },
                        new
                        {
                            ID = 13,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2630),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 7
                        },
                        new
                        {
                            ID = 14,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2631),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 7
                        },
                        new
                        {
                            ID = 15,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2632),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 8
                        },
                        new
                        {
                            ID = 16,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2633),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 8
                        },
                        new
                        {
                            ID = 17,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2634),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 9
                        },
                        new
                        {
                            ID = 18,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2635),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 9
                        },
                        new
                        {
                            ID = 19,
                            Date = new DateTime(2023, 2, 15, 23, 41, 6, 470, DateTimeKind.Local).AddTicks(2636),
                            Description = "There are many variations of passages of Lorem Ipsum",
                            IsDeleted = false,
                            NoteId = 9
                        });
                });

            modelBuilder.Entity("NoteAppAPI.Models.Entity.SubNote", b =>
                {
                    b.HasOne("NoteAppAPI.Models.Entity.Note", "Note")
                        .WithMany("SubNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("NoteAppAPI.Models.Entity.Note", b =>
                {
                    b.Navigation("SubNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
